export const currentPlayingActionTypes = {
  GET_CURRENT_PLAYING_START: "GET_CURRENT_PLAYING_START",
  GET_CURRENT_PLAYING_SUCCESS: "GET_CURRENT_PLAYING_SUCCESS",
  GET_CURRENT_PLAYING_FAILED: "GET_CURRENT_PLAYING_FAILED",
};
