export const featuredPlaylistActionTypes = {
  GET_FEATURED_PLAYLIST_START: "GET_FEATURED_PLAYLIST_START",
  GET_FEATURED_PLAYLIST_SUCCESS: "GET_FEATURED_PLAYLIST_SUCCESS",
  GET_FEATURED_PLAYLIST_FAILED: "GET_FEATURED_PLAYLIST_FAILED",
};
