export const myPlaylistsActionTypes = {
  GET_MY_PLAYLISTS_START: "GET_MY_PLAYLISTS_START",
  GET_MY_PLAYLISTS_SUCCESS: "GET_MY_PLAYLISTS_SUCCESS",
  GET_MY_PLAYLISTS_FAILED: "GET_MY_PLAYLISTS_FAILED",
};
