export const getTrackAnalysisActionTypes = {
  GET_TRACK_ANALYSIS_START: "GET_TRACK_ANALYSIS_START",
  GET_TRACK_ANALYSIS_SUCCESS: "GET_TRACK_ANALYSIS_SUCCESS",
  GET_TRACK_ANALYSIS_FAILED: "GET_TRACK_ANALYSIS_FAILED",
};
