export const transferUserPlaybackActionTypes = {
  TRANSFER_USER_PLAYBACK_START: "TRANSFER_USER_PLAYBACK_START",
  TRANSFER_USER_PLAYBACK_SUCCESS: "TRANSFER_USER_PLAYBACK_SUCCESS",
  TRANSFER_USER_PLAYBACK_FAILED: "TRANSFER_USER_PLAYBACK_FAILED",
};
