export const recentPlayedTracksActionTypes = {
  GET_RECENT_PLAYED_TRACKS_START: "GET_RECENT_PLAYED_TRACKS_START",
  GET_RECENT_PLAYED_TRACKS_SUCCESS: "GET_RECENT_PLAYED_TRACKS_SUCCESS",
  GET_RECENT_PLAYED_TRACKS_FAILED: "GET_RECENT_PLAYED_TRACKS_FAILED",
};
