export const newReleasedTracksActionTypes = {
  GET_NEW_RELEASED_TRACKS_START: "GET_NEW_RELEASED_TRACKS_START",
  GET_NEW_RELEASED_TRACKS_SUCCESS: "GET_NEW_RELEASED_TRACKS_SUCCESS",
  GET_NEW_RELEASED_TRACKS_FAILED: "GET_NEW_RELEASED_TRACKS_FAILED",
};
